name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions

on:

  push:

  workflow_dispatch:
  
  pull_request:
    types: [opened, reopened]


jobs:

  Explore-GitHub-Actions:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - run: python app.py
